### ISSUE TITLE
Include https://www.npmjs.com/package/@solid-data-modules/contacts-rdflib without a build process

### ISSUE THREAD

**Issue by michielbdejong** [michielbdejong/sample-solid-app#1]
I'm working through https://dev.to/sait/js-modules-are-now-supporting-in-browsers-13fn to see if I can include this dependency in the same way you would add jQuery etc to your app, so by just adding a script tag, without having to add a build process.

**Comment by michielbdejong** [comment]
It worked a little bit and [using a serve.json file to control how `npx serve` behaves](https://github.com/michielbdejong/sample-solid-app/blob/main/serve.json) helped, but then I ran into:
```
Uncaught TypeError: Failed to resolve module specifier "@solid-data-modules/contacts-rdflib". Relative references must start with either "/", "./", or "../".
```
I was able to work around this by using the full path to `node_modules` here:
https://github.com/michielbdejong/sample-solid-app/blob/c162dce1164be8e1743cc27c855a66fcf36965db/list-address-books.mjs#L1-L2

But then still I see this error, I guess this is obviously because deeper down it does use node_modules dependencies:
```
Uncaught TypeError: Failed to resolve module specifier "rdflib". Relative references must start with either "/", "./", or "../".
```

**Comment by michielbdejong** [comment]
So my conclusion is that this is probably not possible, and what we need is a webpack build of the contacts data module for me to use it in the same way people used to include jQuery in their html page back in the day. :)

**Comment by angelo-v** [comment]
I think what you are looking for is an esm import map, see https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script/type/importmap

Keep in mind that the data module only has rdflib as a peer dependency so you need to install and map that as well

**Comment by michielbdejong** [comment]
That worked a little bit! I had to install the `short-unique-id` package though, and use the esm/index.js of rdflib instead of the rdflib.min.js.

It now complains that:
```
Uncaught TypeError: Failed to resolve module specifier "@babel/runtime/helpers/createClass". Relative references must start with either "/", "./", or "../".
```
I'm going to stop here and just use a built app but it was nice to learn a bit about this!

**Comment by michielbdejong** [comment]
I'm working around it for now - will leave this sample app as it is and use something else (which does have a build step) to work with data modules.
